CHANGELOG.md
README.md
example/README.md
pubspec.yaml

Added documentation for the Pinwheel Flutter SDK.
> Implement [PP-5059](https://pinwheel.atlassian.net/browse/PP-5059)

Updated readmes

---

ios/pinwheel.podspec

Bump iOS to latest version 2.3.6

Bump iOS version

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Release 0.0.2

---

android/build.gradle
android/consumer-rules.pro

Add R8 rule to keep PinwheelPlugin classes
Problem with minifying on Android #5

Add consumer r8 rules

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Add support for login_attempt event

Release 2.3.0

---

android/build.gradle
example/ios/Podfile.lock
ios/pinwheel.podspec
lib/models.dart
lib/models.g.dart

Add support for platformId in success event payload

Add support for platformId in success event payload

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Release for platformId in success event payload

Release for platformId in success event payload

---

android/build.gradle
android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
example/android/app/build.gradle
example/android/build.gradle
example/android/settings_aar.gradle
example/ios/Podfile.lock
example/pubspec.lock
ios/Classes/SwiftPinwheelPlugin.swift
ios/pinwheel.podspec
pubspec.yaml

Add support for input_required event

Add support for input_required event

---

CHANGELOG.md

- Add support for input_required event.
- Added by [Robby Abaya](https://github.com/rawbee) in Pull Request [#16](https://github.com/underdog-tech/pinwheel-flutter-sdk/pull/16).

Release 2.3.2

---

CHANGELOG.md
pubspec.yaml

Release 2.3.3

---

pubspec.yaml

Update built value to `>=8.3.2 <9.0.0`
> Fix [#1]()

Update built value

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Release 2.3.4

---

README.md
android/build.gradle
android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/pubspec.lock
ios/Classes/SwiftPinwheelPlugin.swift
ios/pinwheel.podspec
lib/models.dart
lib/models.g.dart
lib/pinwheel.dart
lib/serializers.dart
lib/serializers.g.dart
pubspec.lock
pubspec.yaml

Add support for input allocation

Add support for input allocation

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

Release 2.3.5

---

.vscode/settings.json
android/build.gradle
android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
example/android/app/build.gradle
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/profile/AndroidManifest.xml
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

- Update Kotlin
- Make event switch exhaustive
- Update android gradle plugin

Updated Android

---

CHANGELOG.md
pubspec.yaml

- Updated Android project
- Added by [Robby Abaya](https://github.com/rawbee) in Pull Request [#18](https://github.com/underdog-tech/pinwheel-flutter-sdk/pull/25).

Release 2.3.6

---

android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
ios/Classes/SwiftPinwheelPlugin.swift

Fix version tracking

---

example/lib/main.dart
example/lib/token.dart

We now require an API version with all requests. This PR sets the API version for link token requests to the latest
> Fix [#1]()

Add specific API version to link token request

---

android/build.gradle
android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
example/android/build.gradle
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/Info.plist
example/pubspec.lock
ios/Classes/SwiftPinwheelPlugin.swift
ios/pinwheel.podspec
lib/models.dart
lib/models.g.dart
lib/pinwheel.dart
lib/serializers.dart
lib/serializers.g.dart
pubspec.lock
pubspec.yaml

Core 1217 bump android and ios

---

CHANGELOG.md

Release 3.0.0 changelog entry

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/getpinwheel/pinwheel/PinwheelPlugin.kt
example/pubspec.lock
ios/Classes/SwiftPinwheelPlugin.swift
pubspec.yaml

Bumps to V3.1.0 to kick off a new release. Updates README and CHANGELOG.
> Fix [#1]()

Bump to V3.1.0
